# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20160211_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='quartile',
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='impact_factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='quartile',
            field=models.CharField(blank=True, choices=[(b'Q1', b'Q1'), (b'Q2', b'Q2'), (b'Q3', b'Q3'), (b'Q4', b'Q4'), (None, b'None')], default=None, max_length=25, null=True),
        ),
    ]
