apiVersion: v1
kind: Service
metadata:
  name: labman-django
  namespace: labman-web
spec:
  selector:
    app: labman-django
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: labman-nginx
  namespace: labman-web
spec:
  selector:
    app: labman-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: labman-db
  namespace: labman-web
spec:
  selector:
    app: labman-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
