apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labman-static
  namespace: labman-${CICD_GIT_BRANCH}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labman-db
  namespace: labman-${CICD_GIT_BRANCH}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

